name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Build and tests (add steps for building/testing here)

    - name: Create a web release
      run: make web

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Release
        path: releases/web
